services:
  - type: web
    name: blogproject
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn blogproject.wsgi:application